#
# Template docker-compose.yml for redis stack
#

version: '3'

services:

  redis-stack:
    container_name: redis-stack
    hostname: redis-stack
    image: redis/redis-stack:6.2.6-v7            # contains both Redis Stack server and RedisInsight
    #image: redis/redis-stack-server:6.2.6-v7    # provides Redis Stack but excludes RedisInsight
    #image: redis:7.0.8-alpine                   # just redis
    restart: unless-stopped
    labels:
      - autoheal=true
      - monocker.enable=true
      - diun.enable=true
    #networks:
    #  - servicename
    ports:
    # - 6379:6379   # redis port
      - 6380:8001   # redis insight webui
    #environment:
    # - REDIS_ARGS="--save 30 1 --loglevel warning"
    # - REDISTIMESERIES_ARGS="RETENTION_POLICY=20"
    volumes:
      - ./redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      start_period: 30s
      timeout: 10s
      retries: 3
    #mem_limit: 40m
    #memswap_limit: 40m
    #mem_reservation: 20m
    #cpu_shares: 1024
    #cpus: 0.5
    #logging:
    #  driver: "none"
