###
### Template compose.yaml for A.R.M. (Automatic Ripping Machine)
### with Intel QSV enabled
###
### https://github.com/automatic-ripping-machine/automatic-ripping-machine
###
### Create bind mounts on host before start, make sure owner matches
### the vars ARM_UID and ARM_GID
###
### Make sure to follow the ARM documentation to map your disc drives
###
services:
  arm-qsv:
    container_name: arm-qsv
    image: automaticrippingmachine/automatic-ripping-machine:latest
    restart: unless-stopped
    networks:
      - arm-qsv
    ports:
      - 8080:8080
    environment:
      - ARM_UID=1000
      - ARM_GID=1000
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    # - /dev/sr0:/dev/sr0
    # - /dev/sr1:/dev/sr1
    # - /dev/sr2:/dev/sr2
    # - /dev/sr3:/dev/sr3
    volumes:
      - ./config:/etc/arm/config
      - ./arm:/home/arm
      - ./logs:/home/arm/logs
      - ./music:/home/arm/music
      - ./media:/home/arm/media
  # mem_limit: 40m
  # memswap_limit: 40m
  # mem_reservation: 20m
  # cpus: 0.5

networks:
  arm-qsv:
    name: arm-qsv
