###
### Template compose.yaml for a new service
###
services:
  example:
    container_name: example
    image: REPLACEME:tag
    restart: unless-stopped
    networks:
      - example
    ports:
      - 8080:80
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    volumes:
      - ./host/path:/container/path
      - example:/container/path
  # healthcheck:
  #   test: "wget --no-verbose --tries=1 --spider --no-check-certificate http://localhost:3000 || exit 1"
  #   test: "curl --fail -s http://localhost:5000/ || exit 1"
  #   test: curl --fail -s http://localhost:5984/_up | grep -Eo '\"status\":\"ok\"' || exit 1
  #   test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
  #   test: ['CMD-SHELL', 'nc -z 127.0.0.1 4822 || exit 1']
  #   test: ['CMD-SHELL', 'pgrep -x "node" || exit 1']
  #   start_period: 60s
  #   start_interval: 30s
  #   interval: 15s
  #   timeout: 5s
  #   retries: 3
  # mem_limit: 40m
  # memswap_limit: 40m
  # mem_reservation: 20m
  # cpus: 0.5

volumes:
  example:
    name: example

networks:
  example:
    name: example
