#
# Template docker-compose.yml for influxdb2
#

version: "3.3"

networks:
  dockernet:
    external: true

services:

  influxdb2:
    container_name: influxdb2
    image: influxdb:2.6.1-alpine
    restart: unless-stopped
    labels:
      - autoheal=true
      - monocker.enable=true
      - diun.enable=true
    networks:
      - dockernet
    ports:
      - 8086:8086
    environment:
      - TZ=Europe/Berlin
      #- PUID=1000
      #- PGID=1000
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=superuser
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=organization
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket
      - INFLUXD_REPORTING_DISABLED=true
    volumes:
      - ./data:/var/lib/influxdb2
      - ./config:/etc/influxdb2
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider --no-check-certificate http://localhost:8086/ping || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
    #mem_limit: 40m
    #memswap_limit: 40m
    #mem_reservation: 20m
    #cpu_shares: 1024
    #cpus: 0.5
    #logging:
    #  driver: json-file
    #  options:
    #    max-size: 5m
