###
### Template compose.yaml for InfluxDB v2
###
services:
  influxdb2:
    container_name: influxdb2
    image: influxdb:2.6.1-alpine
    restart: unless-stopped
    networks:
      - dockernet
    ports:
      - 8086:8086
    environment:
      - TZ=Europe/Berlin
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=superuser
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=organization
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket
      - INFLUXD_REPORTING_DISABLED=true
    volumes:
      - ./config:/etc/influxdb2
      - influxdb2:/var/lib/influxdb2
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8086/ping || exit 1"
      start_period: 60s
      start_interval: 30s
      interval: 30s
      timeout: 5s
      retries: 3
  # mem_limit: 40m
  # memswap_limit: 40m
  # mem_reservation: 20m
  # cpus: 0.5

volumes:
  influxdb2:
    name: influxdb2

networks:
  influxdb2:
    name: influxdb2
