#
# Template docker-compose.yml for mongodb
#

version: '3'

services:

  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo:6.0.7
    #image: mongo:4.4.21   # monogdb v5+ requires AVX capable CPU
    restart: unless-stopped
    labels:
      - autoheal=true
      - monocker.enable=true
      - diun.enable=true
    networks:
      - service
    #ports:
    #  - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: example
    volumes:
      - ./mongodb:/data/db
    healthcheck:
      test: mongo --norc --quiet --host=localhost --eval "db.runCommand('ping')" || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    #mem_limit: 40m
    #memswap_limit: 40m
    #mem_reservation: 20m
    #cpu_shares: 1024
    #cpus: 0.5
    #logging:
    #  driver: "none"
