###
### Template compose.yaml for PostgreSQL
###
services:
  postgres:
    container_name: postgres
    image: postgres:16.4-alpine3.20
    restart: unless-stopped
    networks:
      - postgres
    ports:
      - 5432:5432
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ### folder for init scripts can be supplied like this:
    # - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER} -h localhost"]
      start_period: 60s
      start_interval: 30s
      interval: 30s
      timeout: 5s
      retries: 3
  # mem_limit: 100m
  # memswap_limit: 100m
  # mem_reservation: 75m
  # cpus: 0.5

volumes:
  postgres:
    name: postgres

networks:
  postgres:
    name: postgres
