###
### Template compose.yaml for Redis
###
services:
  redis:
    container_name: redis
    image: redis:7.0.8-alpine
    restart: unless-stopped
    networks:
      - redis
    ports:
      - 6379:6379
    command: redis-server --save 30 1 --loglevel warning
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 60s
      start_interval: 30s
      interval: 30s
      timeout: 5s
      retries: 3
  # mem_limit: 40m
  # memswap_limit: 40m
  # mem_reservation: 20m
  # cpus: 0.5

volumes:
  redis:
    name: redis

networks:
  redis:
    name: redis
